# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing OS dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-wxgtk3.0

      - run:
          name: Installing Miniconda
          # Getting Gooey to install properly on standard python is a nightmare, due to the wxpython dependency
          # which is not packaged properly in the CircleCI Ubuntu version. Pip does not work well either.
          # Conda is actually the recommended way to install wx-python according to the wx-python website !
          command: |
            if [ -d "../miniconda3/envs/condaenv" ]; then
              echo "Miniconda already installed, skipping this step"
            else
              echo "Installing Miniconda"
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
              chmod +x ./Miniconda3-latest-Linux-x86_64.sh
              ./Miniconda3-latest-Linux-x86_64.sh -b
              export PATH=$HOME/miniconda3/bin:$PATH
              conda update --quiet --yes conda
              conda create --name condaenv --yes
            fi

      - run:
          name: Installing Python dependencies
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate condaenv
            conda install --quiet --yes -n condaenv wxpython
            conda install --quiet --yes -n condaenv -c sradiouy gooey
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ../miniconda3/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate condaenv
            coverage run --source pyjak -m xmlrunner discover tests
            coverage report
            coverage xml -o test-reports/coverage.xml
            coverage html -d test-reports/html
            mkdir -p test-reports/unittest && mv TEST-*.xml test-reports/unittest

      - run:
          name: CodeCov upload
          command: |
            bash <(curl -s https://codecov.io/bash)

      - run:
          name: Building executable
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate condaenv
            pyinstaller build.spec

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: dist
          destination: dist

      - persist_to_workspace:
          root: .
          paths:
            - dist/*

  deploy:
      working_directory: ~/repo

      docker:
        - image: circleci/python:3.6.1

      steps:
        - checkout
        - attach_workspace:
            at: /tmp/workspace

        - run:
            name: Installing github-release
            command: |
              if [ -d "$HOME/github-release/bin/linux/amd64" ]; then
                echo "github-release already installed, skipping this step"
              else
                echo "Installing github-release"
                mkdir $HOME/github-release
                cd $HOME/github-release
                wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
                tar jxf linux-amd64-github-release.tar.bz2
              fi


        - run:
            name: Releasing new version
            command: |
              export PATH=$HOME/github-release/bin/linux/amd64:$PATH
              cd ~/repo
              previous_version_tag=`git tag -l | tail -2 |head -1`
              current_version_tag=`git describe --tags`
              changelog=`git log ${previous_version_tag}..HEAD --oneline --no-merges | grep -v PRO`
              description=`echo "### Description" && echo "This is Pyjak version ${current_version_tag}." && echo "### Changelog" && echo "Improvements since ${previous_version_tag} are:" && echo "$changelog"`
              github-release edit --user jyannick --repo pyjak --tag ${current_version_tag} --name "${current_version_tag}" --description "${description}"
              github-release upload --user jyannick --repo pyjak --tag ${current_version_tag} --name "Pyjak-${current_version_tag}-linux" --file /tmp/workspace/dist/*

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/



