# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing OS dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-wxgtk3.0

      - run:
          name: Installing Miniconda
          # Getting Gooey to install properly on standard python is a nightmare, due to the wxpython dependency
          # which is not packaged properly in the CircleCI Ubuntu version. Pip does not work well either.
          # Conda is actually the recommended way to install wx-python according to the wx-python website !
          command: |
            if [ -d "../miniconda3/envs/condaenv" ]; then
              echo "Miniconda already installed, skipping this step"
            else
              echo "Installing Miniconda"
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
              chmod +x ./Miniconda3-latest-Linux-x86_64.sh
              ./Miniconda3-latest-Linux-x86_64.sh -b
              export PATH=$HOME/miniconda3/bin:$PATH
              conda update --quiet --yes conda
              conda create --name condaenv --yes
            fi

      - run:
          name: Installing Python dependencies
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate condaenv
            conda install --quiet --yes -n condaenv wxpython
            conda install --quiet --yes -n condaenv -c sradiouy gooey
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ../miniconda3/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate condaenv
            coverage run --source pyjak -m xmlrunner discover tests
            coverage report
            coverage xml -o test-reports/coverage.xml
            coverage html -d test-reports/html
            mkdir -p test-reports/unittest && mv TEST-*.xml test-reports/unittest

      - run:
          name: CodeCov upload
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
